<h2>Recommendation</h2>
<div class="col-m-6">
    <div class="row">
        <form action="/customer/recommendations/add" method="post">
            <input type="email" name="recoEmail" class="input-text required-entry">
            <input type="submit">
        </form>
    </div>
</div>
<script type="text/javascript">
    require(["jquery", 'Magento_Ui/js/modal/alert'], function($, alert){

        /*alert({
            title: $.mage.__('Some title'),
            content: $.mage.__('Some content'),
            actions: {
                always: function(){}
            }
        });*/
    });
</script>
